blank_issues_enabled: false
defaults:
  - name: "From: 留言板"
    filename: message.md
    labels: [blog]
    description: 留言板模板
  - name: Common Issue
    filename: common.md
    labels: []
    description: Common Issue Template
