blank_issues_enabled: true
defaults:
  - name: "From: Message Board"
    filename: message-en.md
    labels: [blog]
    description: Message Board Template
  - name: "From: 留言板"
    filename: message-zh.md
    labels: [blog]
    description: 留言板模板
