blank_issues_enabled: false
defaults:
  - name: "From: 留言板"
    filename: message.md
    labels: [blog]
    description: 留言板模板
  - name: Default Issue
    filename: default.md
    labels: []
    description: 默认问题模板
